name: WimAuto CD

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  cas-devops-modules-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Upload Repo as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: wimauto
          path: ./
